model:
  extractor: "HER"
  word_input_size: 100
  sentence_input_size: 400
  word_lstm_hidden_units: 200
  sentence_lstm_hidden_units: 200
  num_lstm_layers: 2
  num_filters: 100 # feature maps
  kernel_sizes: [1, 2, 3] # H corresponding to K= 3
  decode_hidden_units: 200
  dropout: 0.

vocab_file: "data/vocab"
glove_file: "data/vocab_100d.txt"
embedding_size: 100

pretrained_model_path: "data/best_model_2.pt"
max_length: -1
